### ISSUE TITLE
Ore Bushes are breakable but not place able.

### ISSUE THREAD

**Issue by jtheise** [Lhykos/OreShrubs#1]
I went and found some ore berry bushes in my world (1.11.2) and picked them up. I can no now longer place them back down. I have a room that's perfectly dark just like how the old bushes worked.

**Comment by Lhykos** [comment]
I tested it myself and everything works fine. I mentioned it in two comments on curse.com. Overworld shrubs needs to be placed on regular stone. No cobblestone or something else. Nether shrubs can only be placed on netherrack and End shrubs only on end stone.
If you're can't place them on stone too, it would be good to send me a list of the mods you are using. Then I have to look deeper!
