### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by xannor** [Lhykos/OreShrubs#12]
I finally narrowed down the cause and it seems that oreshrubs when used on a dedicated server will cause the noted exception during world gen/startup. If I remove oreshrubs I can bring the server up.

https://gist.github.com/xannor/b5f43696a8d5249ccbea950544534c6a

This does not happen in single player worlds.

MC 1.12.1
Forge 2474
OreShrubs 1.4.0

NOTE: I just saw your note about it not working in 1.12.1 but I could find nothing related to this issue and as I noted it works find in single player, for me, so hopefully this will help narrow down the incompatibility issue.

NOTE 2: I just also notice that this issue has been reported already. So this is a dupe of #9.

**Comment by Lhykos** [comment]
I already found it. I registered the loot tables for my mod in a static context and minecraft did not like that. >_>
Don't worry I update the mod soon, but currently I want to finish some other things before I release it. :)

**Comment by Lhykos** [comment]
Also done! See 1.4.1.
