### ISSUE TITLE
Custom Shrubs, Specifying Metadata

### ISSUE THREAD

**Issue by Secretname2009** [Lhykos/OreShrubs#16]
Im trying to make a custom shrub, but the produced item has a metadata, how do i specify that in the crafting results in the .json?

**Comment by Lhykos** [comment]
Good that you mentioned it. It seems that github not uploaded the new examples for making a custom shrub. I upload them today! :)

**Comment by Lhykos** [comment]
I answered a question today where you can do this: #20 
I always thought there are examples for that, but I was wrong.

**Comment by Secretname2009** [comment]
Alright, that seems to have worked, although it is some time since i last played minecraft its good to get the answer.
Thanks for the help.

**Comment by Secretname2009** [comment]
Just to clarify, i needed to add "item_meta": in the crafting results and thats that.

**Comment by Lhykos** [comment]
I'm sorry for the late answer, lot of work~
You only can use the meta data tag if you use the "itemstack_result". In the "oredict_result" it have no effect, like here:

> `"itemstack_result": { "item_name": "minecraft:stone", "item_meta": "1", "crafting_amount": 4, "recipe_pattern": [ "***" ] }`

But I found a bug where it currently not work, I fix that today! :)
