### ISSUE TITLE
[1.12.2] Too Many Recipes Added Through Integration

### ISSUE THREAD

**Issue by JonasCiss** [Lhykos/OreShrubs#17]
You can craft every nugget from every ore berry. I also suggest to add smelting recipes instead of crafting recipes. I used NoMoreRecipeConflict mod to see that. 
![2017-12-07_21 20 12](https://user-images.githubusercontent.com/26455012/33736978-ed999052-db94-11e7-9801-d9f0a45ae423.png)
![2017-12-07_21 20 13](https://user-images.githubusercontent.com/26455012/33736980-ede27998-db94-11e7-85e3-473adb85dff1.png)
![2017-12-07_21 20 14](https://user-images.githubusercontent.com/26455012/33736981-ee01b6e6-db94-11e7-9d0f-a5ef723569d9.png)
![2017-12-07_21 20 10](https://user-images.githubusercontent.com/26455012/33736982-ee237768-db94-11e7-825e-16ee67d27411.png)
![2017-12-07_21 20 15](https://user-images.githubusercontent.com/26455012/33736990-f393f3ee-db94-11e7-9f1d-146275e00809.png)
![2017-12-07_21 20 16](https://user-images.githubusercontent.com/26455012/33736992-f4f54e36-db94-11e7-803e-315b0ca197f2.png)
![2017-12-07_21 20 17](https://user-images.githubusercontent.com/26455012/33736993-f5144a84-db94-11e7-8f55-70f37bade50c.png)
![2017-12-07_21 20 18](https://user-images.githubusercontent.com/26455012/33736994-f5352a2e-db94-11e7-8412-f74ae1e75998.png)
![2017-12-07_21 20 19](https://user-images.githubusercontent.com/26455012/33736995-f5687c30-db94-11e7-9357-1746c6238ee1.png)
![2017-12-07_21 20 20](https://user-images.githubusercontent.com/26455012/33736996-f5865250-db94-11e7-81bc-d1d9560b06c4.png)

**Comment by vrork** [comment]
Same here. I was about to make that report
Ps: Nice skin.

**Comment by JonasCiss** [comment]
Thanks, I got that skin from skindex.

http://www.minecraftskins.com/skin/10629015/wither-reborn/

**Comment by Lhykos** [comment]
Thanks. I take a look at it. Which forge version do you use? Could be possible that forge changes something. I remember that it works fine in the first 1.12.2 versions.

**Comment by JonasCiss** [comment]
I use the latest recommended build 1.12.2 - 14.23.1.2555.

**Comment by Lhykos** [comment]
Thank you. I work on it and maybe update it today!

**Comment by JonasCiss** [comment]
That would be nice.
I also got a question. Is there a way to add costum ore shrubs?

**Comment by Lhykos** [comment]
@JonasCiss Yes you can add custom shrubs. In the config folder is a folder named 'shrubs'. Just create a custom shrub and put the file in there. You can take the files from there as examples or look at this file: [How-To-Custom-Shrub](https://github.com/Lhykos/OreShrubs/blob/master/HOWTO-CustomShrubs.md).
You also can configure the existing ones, if you want.

.. to the issue. My mod register all recipes correctly, expect the recipe for the compressed ones. (Idk why nobody tell me about that earlier.). I fixed that one, but I think the main problem is another mod that modifies recipes and not check the nbt data!
When I test my mod without any others, it works fine.

And sadly I also can't register smelting recipes, because minecraft not compare the nbt data by the smelting.
I working on a other system for processing ore berries.

**Comment by JonasCiss** [comment]
Maybe you can name every ore berry with a unique name? Then the nbt data is not important anymore.

**Comment by Lhykos** [comment]
If only my mod is present, everything works fine. As I say before there must be a mod that changes the way recipes are registered or a mod that manipulates recipes. It's no bug from my mod.
Beside that I will remove the nbt stuff from the berries, but in 1.13.
Maybe I'll found a work-around fix.

**Comment by JonasCiss** [comment]
I'll try to find out which mod messes this up.

**Comment by JonasCiss** [comment]
So I use NoMoreRecipeConflict to show the different recipes. But that only works if for every berry every recipe is registered. That means there all recipes registered for every berry to every nugget. 

But I think the intented behavoir is one berry to one specfic nugget. That means only one recipe for one berry. 

Are the recipes generated automatically?

**Comment by Lhykos** [comment]
The recipes are generated automatically, depending on which types are registered,
I write all to a seperate json file (like  normal recipe registration would work) and then load them with the built in recipe loader.

**Comment by JonasCiss** [comment]
Is it not possible to generate .json files automatically?

**Comment by ElvenChaos** [comment]
@JonasCiss Did you happen to be using a mod to unify recipes, such as UniDict or something similar? I've come across the issue as well and I suspect the berries are being negatively affected by the process.

Also, for me crafting a 3x3 of any berry only gives a yellorium ingot from extreme reactors, so something funny is definitely going on on my end with my pack setup.

**Comment by JonasCiss** [comment]
@ElvenChaos Yes I do, but that would only be possible if they are registered as ingots or nuggets.

**Comment by ElvenChaos** [comment]
They may not be nuggets or ingots, but they certainly craft into them. I'll try taking unidict out and creating a new world to test, you should try the same.

**Comment by JonasCiss** [comment]
I will try. If it take effect I will try to blacklist them.

**Comment by JonasCiss** [comment]
I tested this. This issue is actually caused by UniDict.
I think I adds so many recipes because every item has the ID oreberries and it seems for the mod to be one. I had no success to blacklist Oreshrubs to avoid crafting integration. 

However I created a request at UniDicts repo to blacklist whole mods. 
https://github.com/WanionCane/UniDict/issues/73

**Comment by Lhykos** [comment]
Good to know that UniDict is working on a solution.
It's unbelievable that nbt is causing so many compatibility issues between mods...

**Comment by WanionCane** [comment]
"fixed" on the [newest UniDict release](https://minecraft.curseforge.com/projects/unidict/files/2519782), also, I added to this mod be ignored by default, though, this will make the shrubs to not craft the right nuggets. (since Crafting Integration will ignore recipes added by this mod).

**Comment by JonasCiss** [comment]
All recipes now have the right result.
fixed in UniDict 2.3
