### ISSUE TITLE
[1.12] OreShrubs-1.4.2 Infinite Gold from Empty Bag?

### ISSUE THREAD

**Issue by Gbergz** [Lhykos/OreShrubs#18]
^

As the title says, is this supposed to happen?

I got a Loot Bag from a Zombie Villager upon opening it i got the items ofcourse but then it didn't disappear and i got the Empty Bag. But when i'm right clicking this 'Empty Bag' on the ground it spawns a Gold Bush, and the bag doesn't have durability so it's infinite Gold.

GIF With Proof: [Gfycat](https://gfycat.com/DefensiveOccasionalArcticfox)

**Comment by Lhykos** [comment]
Fixed in 1.4.3!
