### ISSUE TITLE
Default 3x3 recipes broken

### ISSUE THREAD

**Issue by ElvenChaos** [Lhykos/OreShrubs#19]
The 3x3 berry to ingot recipes for the default ore shrub entries do not appear when crafting nor in JEI.
This bug seems to pertain to only the entries that ship with the mod, and only the 3v3 berry to ingot ore dict recipes as they appear in the ore shrub entry.
This includes aluminum, ardite, cobalt, copper, tin, gold, iron, lead, nickel. and silver. I have uranium disabled.
Custom entries are unaffected, even if they implement a 3v3 ore dict recipe.
Affected entries can still craft 1 berry to 1 nugget, if the nugget exists.
Attached is the sum of my entries, with ender pearl and uranium being disabled, and yellorium being a custom entry as opposed to being generated by the config option.
[shrubs.zip](https://github.com/Lhykos/OreShrubs/files/1637417/shrubs.zip)

**Comment by Lhykos** [comment]
This is no bug. This behaviour is only done for Ore Dictionary recipes. If the recipe output is a ingot I test if there is a nugget available and replace the ingot recipe with it.
If the Ore Dictionary name is "ingotIron", I test if there is a "nuggetIron", if it exist I replace it. This was a design thing.

Btw. the _ItemStackResult_ must be written as: "itemstack_result" othwise it will not work. I didn't wrote that in the HOWTO file, yet.
