### ISSUE TITLE
[1.12.2] Unable to add OreShrub for Yellorium and unregistered items

### ISSUE THREAD

**Issue by JonasCiss** [Lhykos/OreShrubs#20]
I made custom .json files. I noticed that I can made shrubs for items I had to register with UniDict because they have no standart registration, for example Charged Certus Quartz, Dimensional Shard.

Second Issue is that I cannot add a OreShrub for Yellorium. I think that is why there is no Yellorium nugget. But there is a strange recipe added instead.

**Comment by JonasCiss** [comment]
![2018-01-24_21 35 27](https://user-images.githubusercontent.com/26455012/35359533-bd1069f6-015a-11e8-91a2-d7087bb73968.png)

**Comment by JonasCiss** [comment]
Here are the .jsons I made. Note: mithril is mana infused ingot of Thermal Foundation
[oreshrubs.zip](https://github.com/Lhykos/OreShrubs/files/1661872/oreshrubs.zip)

**Comment by Lhykos** [comment]
If you not changed the config of Extreme Reactors, Yellorum is registered as Uranium.
So Yellorium = Uranium. This recipe is by default disabled in the config of OreShrubs:

> `    # If true, a separate 'Yellorium Inogt' recipe will be registered. Useful if Yellorium is not registered as Uranium. (Default: false)
>     B:enableExtraYellorumRecipe=false`

This recipe is for the case that Yellorum is not registered  as Uranium (in OreDict), that you can craft from the uranium berries a yellorium ingot too.

There is no bug.

**Comment by JonasCiss** [comment]
That makes it clear. Yellorium is not registered as Uranium. I changed that. Then there is no way to create a shrub espacially for Yellorium?

And what about items that are not in the OreDict? Is there a way to create shrubs for them?

**Comment by Lhykos** [comment]
I didn't try it myself but you could use the _ItemStackResult_ and that would answer your second question too,
I noticed that I haven't a example for them,  but you use them like the _OreDictResult_:

`"itemstack_result": {
    "item_name": "minecraft:stone",
    "item_meta": "1",
    "crafting_amount": 4,
    "recipe_pattern": [
      "***"
    ]
  }`

This is also explained in the "HOWTO-CustomShrubs" file.

**Comment by JonasCiss** [comment]
[oreshrubs.zip](https://github.com/Lhykos/OreShrubs/files/1664078/oreshrubs.zip)
I tried this but no ore shrubs were added. Did I do something wrong?

**Comment by Lhykos** [comment]
You did everything right. I did something wrong, a stupid bug.
I fix that today!

**Comment by JonasCiss** [comment]
Ore Shrubs now requires Forge 14.23.1.2662. This version does not exist. the latest ersion of Forge is 14.23.1.2604.

**Comment by Lhykos** [comment]
I reuploaded the file.

**Comment by JonasCiss** [comment]
Everything works now correctly and every shrubs works as intended, thanks!
