### ISSUE TITLE
Freshly generated configuration doesn't include Tin

### ISSUE THREAD

**Issue by esotericist** [Lhykos/OreShrubs#3]
It includes all the other expected mod materials the description says are supported (cobalt, ardite, dark ore, uranium, aluminum, nickel, black quartz, copper, lead, silver) plus all of the expected vanilla (iron, gold, quartz, xp), but tin isn't listed, despite being provided by at least four mods I have loaded.

This is using oreshrubs-1.3.0-1.11.2.jar.

**Comment by Lhykos** [comment]
I know about that and  I will fix it in the next update! :)

**Comment by esotericist** [comment]
Okay, as long as you know. :)

**Comment by Lhykos** [comment]
Should be fixed!
