### ISSUE TITLE
Placing items in crafting grid adds an NBT tag to items causing them not to stack with others (SMP only)

### ISSUE THREAD

**Issue by darkphan** [Lhykos/OreShrubs#4]
Minecraft: 1.11.2
Forge: forge-1.11.2-13.20.0.2366
OreShrubs: 1.3.1

Only loaded Ore Shrubs on server, and taking items off of a stack in your inventory (any item not just Ore Shrubs stuff) and placing them in a crafting grid causes the items to get an NBT tag appended to them, which then prevents those items from stacking with the original.

[Screenshot](http://i.imgur.com/teWybAS.png)

This does not happen with Ore Shrubs 1.3.0.

**Comment by Lhykos** [comment]
Thank you. :) 
I already found the problem. I fix it tomorrow.

**Comment by Lhykos** [comment]
Should be fixed in 1.3.2.
