### ISSUE TITLE
Compatability with Underground Biomes Constructs

### ISSUE THREAD

**Issue by DoragonKeiyou** [Lhykos/OreShrubs#5]
Oreberry Bushes only seem to like vanilla stone, which causes a bit of an issue where 95% of my world is not vanilla stone.  Is it possible for it to check against the ore dictionary for stone, rather than it only being vanilla?

**Comment by Lhykos** [comment]
Which version do you use?
In [1.3.1](https://github.com/Lhykos/OreShrubs/blob/master/Changelog.md#oreshrubs---131) you can place every shrub from the overworld on a solid block, there is no more a limitation..

**Comment by DoragonKeiyou** [comment]
My bad for not specifying.  I am running version 1.2.1 (MC 1.10.2).

**Comment by Lhykos** [comment]
I think I will work on a last update for 1.10.2. :)

**Comment by Lhykos** [comment]
Look at version 1.2.2. :)
