### ISSUE TITLE
Shrub Collector going ham on the door and selling crazy

### ISSUE THREAD

**Issue by Kisutora** [Lhykos/OreShrubs#7]
Many times when I come accross a Shrub Collector he'd be constantly opening and closing his little house's door and I'd have to interact with the door to make him stop. It's quite funny actually.

Also he more often than not will have trades that are identical to one another or almost the same.
![sh2](https://user-images.githubusercontent.com/22685232/28492744-7431b1d0-6f11-11e7-8bc5-e2e99c128ac0.png)
![sh3](https://user-images.githubusercontent.com/22685232/28492745-743331ea-6f11-11e7-8739-02b3009179aa.png)
![sh1](https://user-images.githubusercontent.com/22685232/28492746-7433e1b2-6f11-11e7-9b39-f65dd20217a9.png)

**Comment by Lhykos** [comment]
He is not the smartes guy, but I have a idea to let him out to the sunlight. And I tell him to not sell the stuff twice. :P  
I actually like the textures for my berries and bags, which texturepack do you use?

**Comment by Kisutora** [comment]
Great, you tell him that. ;)
It's a personal resource pack that has assets from other resource packs, some made by me but most are from other resource packs or slightly edited. If I remember correctly the bag is from Unity and the berries are from ItemBound. The compressed berries are from ItemBound as well.
![shurbs](https://user-images.githubusercontent.com/22685232/28493095-cf1ba270-6f18-11e7-9da7-9ae6dd372b4a.png)

**Comment by Lhykos** [comment]
Done! Because this isn't a "trouble making issue" i implemented this change in the update for 1.12! :)
