### ISSUE TITLE
Register smeltery recipe

### ISSUE THREAD

**Issue by ST-DDT** [Lhykos/OreShrubs#8]
It would be nice if the tinker construct smeltery recipes for the berries get automatically registered if TC is available. Because its quite confusing to first "craft" the berries to a nugget before it is possible to smelt them.

**Comment by Lhykos** [comment]
Currently this is not possible, because the smeltery does not compare the nbt tag of my berries. This would mean if you put a berry in the smeltery you would always get molten iron. 
But I see many trouble with the nbt stuff. I will get rid of it in one of the next updates!

**Comment by Lhykos** [comment]
I need to correct myself, I did not know that Tinkers Construct has an API. The next update will support it!

**Comment by Lhykos** [comment]
Done! See 1.4.1!
